import { useEffect, useMemo, useState } from "react";
import { getPlannerAssignments, getTeacherPlanners, savePlanner } from "../repository/PlannerRepository";
import type { PlannerRecord, PlannerType, QuestionItem, QuestionPaperPayload, TeacherAssignmentOption } from "../types/PlannerModels";
import { AssignmentFields, PaperPreview, PlannerHistoryTable, PlannerPageFrame, QuestionEditor, printPlannerRecord } from "../components/PlannerUI";

export default function QuestionPaperPlannerPage({plannerType}:{plannerType:PlannerType}){
  const isUnit=plannerType==="unit_test";
  const [assignments,setAssignments]=useState<TeacherAssignmentOption[]>([]); const [records,setRecords]=useState<PlannerRecord[]>([]); const [preview,setPreview]=useState<PlannerRecord|null>(null); const [editing,setEditing]=useState<PlannerRecord|null>(null);
  const [schoolName,setSchoolName]=useState(""); const [title,setTitle]=useState(isUnit?"Unit Test":"Examination Paper"); const [totalMarks,setTotalMarks]=useState(40); const [timeAllowed,setTimeAllowed]=useState("60 minutes"); const [className,setClassName]=useState(""); const [sectionName,setSectionName]=useState(""); const [subjectName,setSubjectName]=useState(""); const [date,setDate]=useState(""); const [questions,setQuestions]=useState<QuestionItem[]>([]); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  async function load(){try{const [a,r]=await Promise.all([getPlannerAssignments(),getTeacherPlanners(plannerType)]);setAssignments(a);setRecords(r);}catch(e:any){setError(e?.message??"Unable to load paper planners.")}}
  useEffect(()=>{void load()},[plannerType]);
  const computedTotal=useMemo(()=>questions.reduce((s,q)=>s+Number(q.marks||0),0),[questions]);
  function choose(a:TeacherAssignmentOption){setClassName(a.className);setSectionName(a.sectionName);setSubjectName(a.subjectName)}
  function valid(){if(!schoolName||!className||!sectionName||!subjectName||!date||questions.length===0){setError("Complete school, assigned classroom, subject, date and at least one question.");return false}if(computedTotal!==Number(totalMarks)){setError(`Question marks total ${computedTotal}, but paper total is ${totalMarks}.`);return false}return true}
  async function submit(){if(!valid())return;setSaving(true);setError("");try{const payload:QuestionPaperPayload={schoolName,totalMarks:Number(totalMarks),timeAllowed,questions};await savePlanner({plannerType,title,templateKey:"a4-paper",className,sectionName,subjectName,startDate:date,endDate:date,payload,submit:true});setQuestions([]);await load()}catch(e:any){setError(e?.message??"Unable to submit paper.")}finally{setSaving(false)}}
  function newPreview(){if(!valid())return;setPreview({id:"preview",schoolUuid:"",teacherUuid:"",teacherName:"",plannerType,title,templateKey:"a4-paper",className,sectionName,subjectName,startDate:date,endDate:date,payload:{schoolName,totalMarks:Number(totalMarks),timeAllowed,questions},status:"DRAFT",reviewNote:"",submittedAt:null,reviewedAt:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}
  async function saveEdited(payload:QuestionPaperPayload){if(!editing)return;setSaving(true);try{await savePlanner({id:editing.id,plannerType,title:editing.title,templateKey:editing.templateKey,className:editing.className,sectionName:editing.sectionName,subjectName:editing.subjectName,startDate:editing.startDate,endDate:editing.endDate,payload,submit:true});setEditing(null);await load()}catch(e:any){setError(e?.message??"Unable to save edits.")}finally{setSaving(false)}}
  function download(r:PlannerRecord){printPlannerRecord(r)}
  return <PlannerPageFrame title={isUnit?"Unit Test Planner":"Exam Paper Planner"} eyebrow={isUnit?"UNIT TEST PLANNING WORKSPACE":"EXAM PAPER PLANNING WORKSPACE"} copy="Prepare a structured A4-ready paper using prebuilt question types, mark allocation and a compact preview/edit workflow designed for teacher mobile and tablet use.">
    {error&&<div className="planner-section" style={{background:"#FEF2F2",borderColor:"#FECACA",color:"#B91C1C",fontSize:10,fontWeight:800}}>{error}</div>}
    <section className="planner-section"><div className="planner-section-head"><div><div className="planner-eyebrow">01 · Paper setup</div><h2 className="planner-section-title">Save the paper details</h2><p className="planner-section-copy">The classroom dropdown uses your existing teacher assignment data.</p></div></div><div className="planner-grid"><div className="planner-field"><label>School name</label><input value={schoolName} onChange={(e: any)=>setSchoolName(e.target.value)} placeholder="School name"/></div><div className="planner-field"><label>Paper title</label><input value={title} onChange={(e: any)=>setTitle(e.target.value)}/></div><div className="planner-field"><label>Total marks</label><input type="number" min={1} value={totalMarks} onChange={(e: any)=>setTotalMarks(Number(e.target.value))}/></div><div className="planner-field"><label>Time allotted</label><input value={timeAllowed} onChange={(e: any)=>setTimeAllowed(e.target.value)} placeholder="60 minutes"/></div></div><AssignmentFields assignments={assignments} className={className} sectionName={sectionName} subjectName={subjectName} onSelect={choose}/><div className="planner-grid"><div className="planner-field"><label>Date</label><input type="date" value={date} onChange={(e: any)=>setDate(e.target.value)}/></div><div className="planner-field"><label>Day</label><input value={date?new Date(date).toLocaleDateString("en-IN",{weekday:"long"}):""} readOnly placeholder="Auto from date"/></div></div></section>
    <section className="planner-section"><div className="planner-section-head"><div><div className="planner-eyebrow">02 · Questions</div><h2 className="planner-section-title">Build the paper</h2><p className="planner-section-copy">MCQ, short answer, long answer, match columns, fill in the blanks, true/false, image-based questions and unseen passages. Add as many questions as needed.</p></div><span style={{fontSize:10,fontWeight:800,color:computedTotal===Number(totalMarks)?"#15803D":"#C2410C"}}>{computedTotal} / {totalMarks} marks</span></div><QuestionEditor questions={questions} onChange={setQuestions}/><div className="planner-actions" style={{marginTop:12}}><button className="planner-btn" onClick={newPreview}>Preview A4</button><button className="planner-btn primary" disabled={saving} onClick={submit}>{saving?"Submitting…":"Save & Submit"}</button></div></section>
    <section className="planner-section"><div className="planner-section-head"><div><div className="planner-eyebrow">03 · History</div><h2 className="planner-section-title">Published paper history</h2><p className="planner-section-copy">View, edit and use the PDF print flow from the same compact scrollable table.</p></div></div><PlannerHistoryTable records={records} onView={setPreview} onEdit={setEditing} onDownload={download}/></section>
    {preview&&<PaperPreview record={preview} onClose={()=>setPreview(null)}/>} {editing&&<PaperPreview record={editing} editable onClose={()=>setEditing(null)} onSaveEdit={saveEdited}/>} 
  </PlannerPageFrame>;
}
