import React from "react";

const benefits=["Premium academies near you","Exclusive scholarships","Live auditions","Workshops & masterclasses","Sports and arts pathways","Verified opportunity discovery"];

export default function MarketplacePage(){
 return <section className="market-page"><div className="market-inner">
   <div className="market-text"><div className="kicker">OPPORTUNITY MARKETPLACE</div><h1>A World of Opportunities, Right at Your Fingertips</h1><p>Growth doesn’t stop when the school bell rings. Our platform bridges the gap between digital skill-tracking and real-world talent development by connecting you directly with premium academies and institutes right in your neighborhood. Discover tailored learning programs, unlock exclusive scholarships, and step into the spotlight with live auditions. Whether you are looking to master an art form, excel in sports, or join elite training programs, the right mentor is just a tap away.</p></div>
   <div className="market-layout"><div className="market-media"><img src="/landing/marketplace.webp" alt="Marketplace opportunities" draggable="false"/></div><div className="benefits">{benefits.map((b,i)=><div key={b}><b>0{i+1}</b><span>{b}</span></div>)}</div></div>
 </div><style>{`
 .market-page{padding:48px 17px 85px;background:#f8fbff}.market-inner{max-width:1180px;margin:auto}.kicker{color:#f5a623;font-size:12px;font-weight:900;letter-spacing:.18em}.market-text h1{font-size:clamp(38px,6vw,68px);line-height:1.02;letter-spacing:-.05em;color:#14213d;max-width:900px;margin:13px 0}.market-text p{font-size:clamp(16px,2vw,20px);line-height:1.75;color:#596982;max-width:920px}.market-layout{display:grid;grid-template-columns:1.35fr .65fr;gap:24px;align-items:stretch;margin-top:35px}.market-media{background:#fff;border-radius:26px;overflow:hidden;border:1px solid #e2e9f2;box-shadow:0 24px 60px rgba(20,33,61,.1)}.market-media img{width:100%;height:100%;display:block;object-fit:contain}.benefits{display:grid;gap:10px}.benefits div{background:#fff;border:1px solid #e2e9f2;border-radius:18px;padding:18px;display:flex;gap:13px;align-items:center;box-shadow:0 10px 25px rgba(20,33,61,.05)}.benefits b{color:#f5a623}.benefits span{color:#34445d;font-weight:700}@media(max-width:800px){.market-layout{grid-template-columns:1fr}.market-media{max-height:none}.benefits{grid-template-columns:1fr 1fr}}@media(max-width:520px){.market-page{padding:38px 15px 65px}.market-text h1{font-size:37px}.market-text p{font-size:16px;line-height:1.65}.market-media{border-radius:18px}.benefits{grid-template-columns:1fr}.benefits div{padding:15px}}
 `}</style></section>
}
