import React from "react";

export default function StarPerformerPage(){
 return <section className="star-page"><div className="star-inner">
  <div className="star-copy"><div className="kicker">TEACHER RECOGNITION</div><h1>Celebrate the Teacher Who Moves the Whole Classroom Forward.</h1><p>Each month, Talent Passport collaborates with participating schools to recognise a teacher who performs exceptionally across the school. The Star Performer is selected through meaningful classroom intelligence—especially doubt closure rate, understanding percentage and sustained learning response.</p><p>We provide a certificate from Talent Passport in collaboration with the school, giving exceptional teachers the recognition they deserve and creating a visible culture of high-performance teaching.</p><div className="star-points"><span>✓ Maximum doubt closure</span><span>✓ Strong understanding percentage</span><span>✓ Consistent classroom improvement</span></div></div>
  <div className="certificate"><img src="/landing/certificate.webp" alt="Teacher recognition certificate" draggable="false"/></div>
 </div><style>{`
 .star-page{padding:48px 17px 85px;background:#fff}.star-inner{max-width:1180px;margin:auto;display:grid;grid-template-columns:1fr .8fr;gap:35px;align-items:center}.kicker{color:#f5a623;font-size:12px;font-weight:900;letter-spacing:.18em}.star-copy h1{font-size:clamp(38px,5.8vw,65px);line-height:1.03;letter-spacing:-.05em;color:#14213d;margin:13px 0}.star-copy p{color:#596982;font-size:clamp(16px,2vw,19px);line-height:1.7}.star-points{display:grid;gap:9px;margin-top:20px}.star-points span{padding:12px 15px;border-radius:13px;background:#f7f9fc;color:#34445d;font-weight:700;border:1px solid #e2e9f2}.certificate{background:#f8fafc;border:1px solid #e2e9f2;border-radius:28px;padding:20px;box-shadow:0 25px 70px rgba(20,33,61,.11)}.certificate img{display:block;width:100%;height:auto;object-fit:contain;user-select:none;-webkit-user-drag:none}@media(max-width:800px){.star-inner{grid-template-columns:1fr}.certificate{order:-1}}@media(max-width:520px){.star-page{padding:38px 15px 65px}.star-copy h1{font-size:37px}.star-copy p{font-size:16px;line-height:1.65}.certificate{padding:12px;border-radius:18px}.star-points span{font-size:13px}}
 `}</style></section>
}
