import { useEffect, useMemo, useState } from "react";
import { getStudentDailyVerificationState, submitStudentDailyVerification } from "../service/StudentDailyVerificationService";
import type { StudentDailyVerificationRow } from "../types/MonthlyLearningReviewTypes";
import LiveDoubtReconciliationGate from "../../liveDoubtIntelligence/components/LiveDoubtReconciliationGate";

interface Props { onSubmitted?: () => void; }
export default function DailyCanonicalVerificationGate({ onSubmitted }: Props) {
  const [subjects, setSubjects] = useState<Array<{subjectName:string;doubts:StudentDailyVerificationRow[]}>>([]);
  const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState(""); const [fallback,setFallback]=useState(false);
  const [answers,setAnswers]=useState<Record<string,"RESOLVED"|"UNRESOLVED">>({});
  function missingInfrastructure(e:any){const m=String(e?.message??e??"").toLowerCase();return m.includes("tp_learning_verification_projection")||m.includes("tp_learning_verification_history")||m.includes("tp_sync_student_verification_projection")||m.includes("tp_submit_student_daily_verification")||m.includes("schema cache")||m.includes("does not exist");}
  async function load(){setLoading(true);setError("");try{const r=await getStudentDailyVerificationState();setSubjects(r.eligibleSubjects);setAnswers({});setFallback(false);}catch(e:any){console.error("DAILY CANONICAL VERIFICATION FAILED — PRESERVING EXISTING LIVE GATE",e);setFallback(true);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const total=useMemo(()=>subjects.reduce((n,s)=>n+s.doubts.length,0),[subjects]);
  const unanswered=subjects.flatMap(s=>s.doubts).filter(d=>!answers[d.learningIdentityKey]);
  async function submit(){if(submitting||unanswered.length)return;setSubmitting(true);setError("");try{await submitStudentDailyVerification(subjects.map(s=>({subjectName:s.subjectName,doubts:s.doubts.map(d=>({id:d.id,sourceLiveId:d.sourceLiveId,sourceMonthlyItemId:d.sourceMonthlyItemId,sourceProjectionId:String(d.sourceProjectionId ?? d.id),learningIdentityKey:d.learningIdentityKey,responseState:answers[d.learningIdentityKey]}))})));setSubjects([]);onSubmitted?.();}catch(e:any){console.error("DAILY VERIFICATION SUBMISSION FAILED — PRESERVING EXISTING LIVE GATE",e);setFallback(true);}finally{setSubmitting(false);}}
  if(loading)return null;
  if(fallback)return <LiveDoubtReconciliationGate onSubmitted={onSubmitted}/>;
  if(subjects.length===0&&!error)return null;
  return <div className="fixed inset-0 z-[99998] flex items-center justify-center p-2 sm:p-4" style={{background:"rgba(7,20,45,.66)",backdropFilter:"blur(12px)"}} role="dialog" aria-modal="true">
    <div className="relative flex max-h-[94vh] w-full max-w-[760px] flex-col overflow-hidden rounded-[22px] border border-white/70 bg-white shadow-[0_24px_80px_rgba(7,20,45,.28)]">
      <div className="shrink-0 border-b border-slate-200 bg-gradient-to-r from-orange-50 via-white to-blue-50 px-4 py-3"><p className="text-[8px] font-black uppercase tracking-[0.22em] text-orange-600">Live Learning Verification</p><div className="mt-1 flex items-center justify-between gap-3"><h2 className="text-[17px] font-black text-[#07142D] sm:text-[20px]">Confirm what is still unresolved</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[8px] font-black text-slate-600">{total} doubts</span></div><p className="mt-1 text-[9px] font-semibold text-slate-500">This verification is built from current canonical intelligence. Select the items that are now resolved; leave the others unresolved.</p></div>
      <div className="min-h-0 flex-1 overflow-y-auto px-3 py-3 sm:px-4"><div className="grid grid-cols-1 gap-3 md:grid-cols-2">{subjects.map(s=><section key={s.subjectName} className="overflow-hidden rounded-2xl border border-slate-200"><div className="flex items-center justify-between border-b bg-slate-50 px-3 py-2"><div className="text-[10px] font-black text-[#07142D]">{s.subjectName}</div><div className="text-[8px] font-bold text-slate-400">{s.doubts.length}</div></div><div className="space-y-1 p-2">{s.doubts.map(d=>{const v=answers[d.learningIdentityKey];return <div key={d.learningIdentityKey} className="rounded-xl border border-slate-100 bg-white p-2"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="text-[9px] font-black text-[#07142D]">{d.topicName||"Topic"}</div><div className="mt-0.5 text-[8px] font-semibold leading-3 text-slate-500">{d.doubtText}</div></div><span className="shrink-0 rounded-full bg-slate-100 px-1.5 py-1 text-[7px] font-black text-slate-400">{d.canonicalDate}</span></div><div className="mt-2 grid grid-cols-2 gap-1.5"><button type="button" disabled={submitting} onClick={()=>setAnswers(a=>({...a,[d.learningIdentityKey]:"RESOLVED"}))} className={`rounded-lg border px-2 py-1.5 text-[8px] font-black ${v==="RESOLVED"?"border-green-400 bg-green-50 text-green-700":"border-slate-200 bg-slate-50 text-slate-500"}`}>✓ Resolved</button><button type="button" disabled={submitting} onClick={()=>setAnswers(a=>({...a,[d.learningIdentityKey]:"UNRESOLVED"}))} className={`rounded-lg border px-2 py-1.5 text-[8px] font-black ${v==="UNRESOLVED"?"border-orange-400 bg-orange-50 text-orange-700":"border-slate-200 bg-slate-50 text-slate-500"}`}>Still unresolved</button></div></div>})}</div></section>)}</div>{error&&<div className="mt-3 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-[9px] font-bold text-red-700">{error}</div>}</div>
      <div className="shrink-0 border-t border-slate-200 bg-white px-3 py-3 sm:px-4"><button type="button" disabled={submitting||unanswered.length>0} onClick={()=>void submit()} className="w-full rounded-xl bg-[#0F2F63] px-4 py-3 text-[9px] font-black uppercase tracking-wider text-white disabled:opacity-50">{submitting?"Saving verification…":"Confirm & continue"}</button>{unanswered.length>0&&<p className="mt-1.5 text-center text-[8px] font-black text-amber-600">Answer every displayed doubt before continuing.</p>}</div>
    </div>
  </div>;
}
