import {useEffect,useState} from "react";
import type {SchoolAcademicYear} from "../models/AcademicYearModels";
import {closeSchoolAcademicYear,createSchoolAcademicYear,getAcademicYearOnboardingSummary,getSchoolAcademicYears,setSchoolAcademicYearCurrent} from "../repositories/AcademicYearRepository";

export default function AcademicYearManagementPanel({schoolUuid,schoolName}:{schoolUuid:string;schoolName?:string}){
 const[years,setYears]=useState<SchoolAcademicYear[]>([]);const[summary,setSummary]=useState<Record<string,any>>({});const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[code,setCode]=useState("");const[name,setName]=useState("");const[startDate,setStartDate]=useState("");const[endDate,setEndDate]=useState("");const[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const rows=await getSchoolAcademicYears(schoolUuid);setYears(rows);const pairs=await Promise.all(rows.map(async y=>[y.id,await getAcademicYearOnboardingSummary(y.id)] as const));setSummary(Object.fromEntries(pairs));}catch(e:any){setError(e?.message??"Unable to load academic years.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[schoolUuid]);
 async function create(){if(!code.trim()||!name.trim()||!startDate||!endDate){setError("Academic year code, name, start date and end date are required.");return;}if(endDate<=startDate){setError("End date must be after the start date.");return;}setSaving(true);setError("");try{await createSchoolAcademicYear({schoolUuid,academicYearCode:code,academicYearName:name,startDate,endDate});setCode("");setName("");setStartDate("");setEndDate("");await load();}catch(e:any){setError(e?.message??"Unable to create academic year.");}finally{setSaving(false);}}
 async function activate(id:string){if(!window.confirm("Activate this academic year? The previous current year will become historical read-only data."))return;setSaving(true);setError("");try{await setSchoolAcademicYearCurrent(id);await load();}catch(e:any){setError(e?.message??"Unable to activate academic year.");}finally{setSaving(false);}}
 async function close(id:string){if(!window.confirm("Close this academic year? Closed years are immutable historical chapters."))return;setSaving(true);setError("");try{await closeSchoolAcademicYear(id);await load();}catch(e:any){setError(e?.message??"Unable to close academic year.");}finally{setSaving(false);}}
 return <section style={{background:"white",borderRadius:16,padding:20,boxShadow:"0 2px 10px rgba(0,0,0,.06)",border:"1px solid #E2E8F0"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12,flexWrap:"wrap"}}><div><h3 style={{margin:0,color:"#143B73"}}>Academic Year Management</h3><p style={{margin:"5px 0 0",color:"#64748B",fontSize:12}}>{schoolName?`${schoolName} · `:""}Creating a new year automatically opens self-service teacher and subscribed-student onboarding. Existing years are never rewritten.</p></div><span style={{fontSize:10,fontWeight:900,color:"#64748B"}}>{loading?"Loading…":`${years.length} year${years.length===1?"":"s"}`}</span></div>{error?<div style={{marginTop:10,padding:9,borderRadius:9,background:"#FEF2F2",color:"#B91C1C",fontSize:10,fontWeight:800}}>{error}</div>:null}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:9,marginTop:14}}><input value={code} onChange={e=>setCode(e.target.value)} placeholder="2027-28" style={inputStyle}/><input value={name} onChange={e=>setName(e.target.value)} placeholder="2027-28" style={inputStyle}/><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} style={inputStyle}/><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} style={inputStyle}/><button type="button" onClick={()=>void create()} disabled={saving} style={primaryStyle}>{saving?"Saving…":"Create Academic Year"}</button></div><div style={{marginTop:14,display:"grid",gap:8}}>{years.map(y=>{const s=summary[y.id]??{};return <div key={y.id} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:10,alignItems:"center",padding:"10px 11px",border:"1px solid #E2E8F0",borderRadius:10}}><div><div style={{fontWeight:900,color:"#0F172A",fontSize:12}}>{y.academicYearName}</div><div style={{marginTop:2,color:"#64748B",fontSize:9}}>{y.startDate} → {y.endDate} · {y.status}</div>{(s.studentPending+s.studentCompleted+s.teacherPending+s.teacherCompleted)>0?<div style={{marginTop:5,color:"#475569",fontSize:9,fontWeight:800}}>Teachers: {s.teacherCompleted??0}/{(s.teacherCompleted??0)+(s.teacherPending??0)} complete · Students: {s.studentCompleted??0}/{(s.studentCompleted??0)+(s.studentPending??0)} complete</div>:null}</div><div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end"}}>{y.isCurrent?<span style={badgeCurrent}>CURRENT</span>:y.status==="PLANNED"?<button type="button" onClick={()=>void activate(y.id)} disabled={saving} style={smallStyle}>Activate</button>:null}{y.status==="ACTIVE"&&!y.isCurrent?<button type="button" onClick={()=>void close(y.id)} disabled={saving} style={smallDangerStyle}>Close</button>:null}</div></div>})}</div></section>}
const inputStyle={width:"100%",boxSizing:"border-box" as const,padding:9,border:"1px solid #CBD5E1",borderRadius:8,fontSize:11};const primaryStyle={padding:"9px 12px",border:0,borderRadius:8,background:"#143B73",color:"white",fontWeight:900,fontSize:10,cursor:"pointer"};const smallStyle={padding:"6px 9px",border:"1px solid #2563EB",borderRadius:7,background:"white",color:"#1D4ED8",fontWeight:900,fontSize:9,cursor:"pointer"};const smallDangerStyle={padding:"6px 9px",border:"1px solid #F97316",borderRadius:7,background:"white",color:"#C2410C",fontWeight:900,fontSize:9,cursor:"pointer"};const badgeCurrent={padding:"5px 7px",borderRadius:999,background:"#DCFCE7",color:"#15803D",fontWeight:900,fontSize:8};
