import type { PortalManualContent } from "./manualTypes";
const page=(id:string,title:string,summary:string,steps:string[],bullets?:string[],note?:string)=>({id,title,summary,steps,bullets,note});
export const PARTNER_MANUAL: PortalManualContent={role:"partner",label:"Partner Portal",intro:"Use the Partner Portal to discover students, create opportunities, review requests and manage the lead pipeline.",sections:[
 page("dashboard","Dashboard","The Partner Dashboard is the starting point for your opportunity activity.",["Open Dashboard.","Read the activity and opportunity information shown for your account.","Use the portal navigation to move to Talent Discovery, Incoming Requests or Lead Pipeline.","Use the relevant workflow when you want to act on a student or opportunity."],["The Partner Portal is designed around talent discovery, opportunities and partner follow-up." ]),

 page("talent-discovery","Talent Discovery","Talent Discovery lets you search the students allocated to the partner and identify students who match your opportunity criteria.",["Open Talent Discovery.","Use School to narrow the list.","Use Class to narrow the list.","Use Event to narrow the list.","Search by Student Name.","Set Minimum Score when you need a score threshold.","Read the student record and event information.","Open the student when you need the full detail.","Choose the relevant action: Offer Scholarship, Offer Workshop or Request Parent Contact."],["The page can show overall student score information and event participation data.","Use filters together when the student pool is large.","The score filter is a selection tool. Review the student's complete record before making an opportunity decision." ]),

 page("talent-metrics","Talent Discovery: Opportunity Metrics","The top cards show what your partner account has already done with opportunities.",["Read Scholarships Offered.","Read Workshops Offered.","Read Contacts Requested.","Read Pending.","Read Accepted.","Read Rejected."],["Scholarships Offered counts scholarship opportunities shared.","Workshops Offered counts workshop invitations created.","Contacts Requested counts consent-based contact requests.","Pending shows opportunities awaiting student response.","Accepted shows opportunities accepted.","Rejected shows opportunities declined." ]),

 page("offer-scholarship","Offer Scholarship","Use this dialog when you want to create a scholarship opportunity for a selected student.",["Select a student in Talent Discovery.","Choose Offer Scholarship.","Enter the scholarship information requested by the form.","Review the opportunity details.","Submit the offer.","Check the offer record after submission."],["The offer is attached to the selected student and becomes part of the partner opportunity record." ]),

 page("offer-workshop","Offer Workshop","Use this dialog when you want to invite a selected student to a workshop opportunity.",["Select a student in Talent Discovery.","Choose Offer Workshop.","Enter the workshop information requested by the form.","Review the invitation details.","Submit the offer.","Check the opportunity record after submission." ]),

 page("request-contact","Request Parent Contact","Use this workflow when you need consent-based parent contact for a selected student.",["Select the student.","Choose Request Parent Contact.","Read the request information.","Submit the request.","Check its status in the opportunity or request area.","Wait for the response before treating the contact request as accepted."],["The Talent Discovery page labels this as a consent-based contact request." ]),

 page("offer-details","Offer Details","Offer Details shows the complete record of an opportunity you created.",["Open View on an opportunity.","Read Offer Type.","Read Status.","Read Student and School.","Check Created and Last Updated.","Review the full opportunity information before editing or sending again." ]),

 page("edit-offer","Edit Offer","Edit Offer lets you update information attached to an existing opportunity.",["Open Edit on the opportunity.","Review the existing values.","Change only the information that needs updating.","Review the updated offer.","Save the changes.","Reopen the record if you want to confirm the update." ]),

 page("incoming-requests","Incoming Requests","Incoming Requests shows student requests and lets you work through pending, accepted and rejected requests.",["Open Incoming Requests.","Read the top metrics.","Search by Student, School or Phone when needed.","Choose the time filter.","Choose Status.","Choose Request Type.","Open a request to read its full details.","Use View, Accept or Reject according to the request state."],["The top metrics are Total Requests, Pending, Accepted and Rejected.","The table can show Student, Request Type, Status, Email, Phone, School, Class and Message.","Time filters include Today, This Week, This Month and Custom when available." ]),

 page("lead-pipeline","Lead Pipeline","Lead Pipeline helps you track partner leads from incoming interest through follow-up and admission outcomes.",["Open Lead Pipeline.","Read Total Leads.","Read Incoming and Outgoing.","Read Admissions and Rejected.","Check Due Today and Overdue.","Check Interested and Counselling.","Search by Student, School, Phone, Time or Type.","Use Status, Source, Time and Type filters.","Open a lead to review or update it."],["Incoming means student-initiated leads in the existing metric description.","Lead types include Scholarship, Workshop and Consultation, with Contact also available in the type filter.","Time filters include All Time, Today, This Week, This Month and This Year." ]),

 page("data-reading","How to read Partner data","Use the metrics as a workflow view. Then open the record behind the metric.",["Start with the top metric.","Apply filters when you need a smaller set.","Open the student or request record.","Read the school, class and event context.","Check the status and last update.","Take the next action in the relevant workflow."],["A top-level count tells you volume. The record tells you what the volume contains.","Use the student detail and opportunity status together before acting."])
]};
