import type { PortalManualContent } from "./manualTypes";
const page=(id:string,title:string,summary:string,steps:string[],bullets?:string[],note?:string)=>({id,title,summary,steps,bullets,note});
export const SCHOOL_ADMIN_MANUAL: PortalManualContent={role:"school",label:"School Admin",intro:"Use School Intelligence to see school-wide learning signals, teacher activity, classroom feedback, academic risk, planning audits, recognition and meeting intelligence.",sections:[
 page("overview","School Health","School Health is the main school-level intelligence view. It gives a quick picture and a classroom-by-classroom diagnostic view.",["Open School Health.","Confirm the Academic Year when the selector is available.","Read the top school metrics first.","Use Class / Section to focus on selected classrooms.","Use Teacher to focus on a teacher.","Read the classroom evidence table.","Open Weekly Meeting Insights when you need the weekly view."],["The overview includes Active Doubts, Doubt Closure Rate, Active Teachers, Classes Reporting and Students.","The classroom diagnostic can show Total Students, Response %, Understanding %, Partial Understanding %, Doubt %, Doubt Closure % and Class Health %.","Response % is the average daily participation rate for the class/section in the selected period.","Class Health % is the average classroom understanding score across feedback-bearing lectures in the selected period." ]),

 page("overview-diagnostic","School Health: Classroom Diagnostic","The Classroom Evidence table lets you compare classes and sections using the same set of learning signals.",["Select one or more Class / Section values when you want a focused comparison.","Select a Teacher when you want to see that teacher's classrooms.","Read Total Students first.","Read Response % to understand feedback participation.","Read Understanding % and Partial Understanding % to see the response mix.","Read Doubt % to see the doubt signal.","Read Doubt Closure % to see how many doubts were resolved.","Read Class Health % for the classroom understanding signal."],["Use selected-class averages when you want a grouped view.","A high Response % with low Understanding % means participation and learning should be read separately.","Doubt Closure % is useful when you want to know whether identified doubts are being resolved, not only whether doubts exist." ]),

 page("teachers","Daily Teacher Logs","Daily Teacher Logs gives the school a teacher-level view of the latest classroom evidence.",["Open Daily Teacher Logs.","Use the Teacher Filter when you want one or more teachers.","Read Latest Lecture Date and Latest Topic.","Check Students Filled Feedback and Feedback Remaining.","Compare Completely Understood, Partially Understood and Didn't Understand.","Read Class Health Score.","Check Most Difficult Concept.","Check Students Requiring Attention."],["The view can show several classrooms under one teacher.","Students Filled Feedback is shown as the submitted count against the classroom student count.","The response mix helps the school distinguish participation from understanding.","Most Difficult Concept and Students Requiring Attention help identify where follow-up may be useful." ]),

 page("classrooms","Classroom Feedback Intelligence","Classroom Feedback Intelligence focuses on the classroom evidence behind school-level learning patterns.",["Open Classroom Feedback Intelligence.","Choose the relevant class or period when filters are available.","Read the feedback participation signal.","Compare understanding and partial understanding.","Check doubt percentage and doubt closure.","Read the class health signal.","Open detailed classroom evidence when a pattern needs investigation."],["Use this view to move from school averages to a classroom-level explanation.","Repeated low understanding or repeated difficult concepts are useful signals for academic follow-up." ]),

 page("academic","Doubt Intelligence","Doubt Intelligence gives the school a preparation and unresolved-doubt view across classes, sections, subjects and teachers.",["Open Doubt Intelligence.","Use Search Student when you need a specific student.","Read the classroom board.","Move horizontally when the board contains many subjects and students.","Read Total Unresolved Doubts.","Read Pending Doubts / Unresolved Subtopics.","Read Highest Risk Topic.","Read Attention Level.","Use the topic and subtopic detail to decide where academic follow-up is needed."],["The board is aggregated class and section wise for the school academic view.","Attention Level is shown for the student-level preparation record.","Use the exact topic and subtopic behind a risk signal before assigning follow-up." ]),

 page("academic-year","Academic Year","Academic Year keeps current-year and historical school intelligence separate.",["Use the Academic Year selector when more than one year is available.","Confirm the selected year before reading analytics.","Review the current year's information when managing the current school year.","Select a previous year when you need historical information.","Return to the current year before continuing current-year work."],["The selector appears only when the school has more than one available academic year.","Always check the selected year before comparing numbers." ]),

 page("lesson-plans","Lesson Planner Audit","Lesson Planner Audit helps the school review lesson-planning activity across teachers and classrooms.",["Open Lesson Planner Audit.","Choose the available period or filter.","Review the planning status shown by the page.","Open the relevant record when detail is needed.","Follow up with the relevant teacher through the teaching workflow."],["Use the audit to check planning activity, not to replace the actual lesson plan." ]),

 page("unit-tests","Unit Test Audit","Unit Test Audit helps the school review unit-test planning activity.",["Open Unit Test Audit.","Choose the relevant period, class or available filter.","Review the audit result.","Open the relevant item for detail.","Follow up with the teacher when required."] ),

 page("exam-papers","Exam Paper Audit","Exam Paper Audit helps the school review exam-paper planning activity.",["Open Exam Paper Audit.","Review the displayed period and class information.","Check the planning status.","Inspect incomplete or exception items when available.","Follow up through the relevant teacher workflow."] ),

 page("worksheets","Worksheet Audit","Worksheet Audit helps the school review worksheet planning and publication activity.",["Open Worksheet Audit.","Choose the available filters.","Read the audit status.","Open the relevant record when detail is needed.","Follow up with the relevant teacher when required."] ),

 page("star-performers","Star Performers","Star Performers gives the school a recognition view for student or classroom performance.",["Open Star Performers.","Read the displayed recognition information.","Use period or class filters when available.","Open details when you need the underlying record.","Use the view for recognition and follow-up alongside the academic evidence."] ),

 page("morning-brief","Morning Brief","Morning Brief is a quick daily school intelligence summary. It helps the school start the day with the most important signals.",["Open Morning Brief when it is shown.","Read the top signals first.","Read the supporting detail.","Note items that need action today.","Open the detailed dashboard area when you need evidence behind a signal.","Close the brief when finished."],["Use Morning Brief as a starting point, not as the only source for a major decision."],"The existing Morning Brief component and intelligence engine are not changed by the manual."),

 page("weekly-insights","Weekly Meeting Insights","Weekly Meeting Insights prepares the school for a weekly review by showing changes and supporting signals.",["Open Weekly Meeting Insights.","Read the headline changes for the week.","Review the supporting teacher, classroom and academic signals.","Note the areas that need discussion.","Open the source dashboard for detailed evidence.","Close the popup to return to the dashboard."],["Use this view to prepare questions and follow-up items for the meeting."],"The existing Weekly Meeting Insights component, repository, view model and engine are not changed."),

 page("analytics-loading","Analytics Loading Popup","The Analytics Loading Popup appears while school intelligence is being prepared.",["Wait for the loading state to finish.","Do not repeatedly refresh while the intelligence is loading.","Continue when the dashboard becomes available."],["This popup is a loading state. It is not a separate analytics result." ]),

 page("statement","Statement / Reports","Use the available statement or report action to keep a record of school information shown by the portal.",["Open the statement or report action when it is available.","Choose the period or filters shown by the report.","Review the information before exporting.","Use the existing download or share action."],["Always check the Academic Year and selected period before exporting a report." ]),

 page("read-data","How to read School Intelligence","Use a simple evidence chain before taking action.",["Start with the school-level signal.","Check the Academic Year and period.","Move from school metrics to teacher or classroom detail.","Open the topic, doubt or student detail behind the signal.","Look for repeated patterns.","Assign follow-up through the relevant teacher or academic workflow."],["Participation and understanding are different signals.","Doubt percentage and doubt closure percentage answer different questions.","Class Health % is a classroom understanding signal for the selected evidence period.","Use detailed evidence before making a student-specific decision."])
]};
