import type { PortalManualContent } from "./manualTypes";

const page = (id:string,title:string,summary:string,steps:string[],bullets?:string[],note?:string) => ({id,title,summary,steps,bullets,note});

export const STUDENT_MANUAL: PortalManualContent = {
  role: "student",
  label: "Student · Academics",
  intro: "Use Academics to understand your learning, give feedback, track progress, revise weak areas and practise with targeted worksheets.",
  sections: [
    page("growth-plan","Academics / Growth Plan","This is your academic learning workspace. It connects your daily learning evidence with progress, revision and practice.",["Open Academics / Growth Plan from your Student Portal.","Start with the tab you need.","Use Daily Feedback after a lesson.","Use Progress Tracker to see change over time.","Use Topic Calendar to see what was taught.","Use Worksheets and Study Buddy when you need practice."],["The pages work together. One page gives evidence. Another page helps you act on that evidence."],"The manual explains the existing student academic workspace. It does not change the feedback or Live Layer logic."),

    page("daily-feedback","Daily Feedback · Loop 1","Daily Feedback tells the portal how well you understood a lesson. It creates the daily learning evidence used by the academic intelligence flow.",["Open Daily Feedback.","Read the class, subject, topic and subtopics for the lecture.","Choose the understanding response shown on screen.","If asked, add the concepts that were difficult.","Submit the feedback once.","After submission, check that the lecture shows your submitted response."],["Your response can show Completely Understood, Partially Understood or Didn't Understand, depending on the existing feedback options.","A successful Daily Feedback submission adds +1 credit in the existing feedback credit flow.","Today's pending feedback is not treated as a missed day yet."],"This is the student-facing name for Loop 1. The manual does not change Loop 1."),

    page("doubt-feedback","Doubt Feedback · Loop 2","Doubt Feedback is the student response step for doubts that need teacher attention or follow-up.",["Open the pending doubt shown in your academic workspace.","Read the topic and doubt information.","Choose the response requested on screen.","Submit the response.","Refresh or return to the list if you want to confirm the doubt is no longer waiting for your action."],["A successful Doubt Feedback response receives the same +1 treatment in the existing feedback credit flow.","Repeated unresolved doubts can become useful signals for later revision and teacher follow-up."],"This is the student-facing name for Loop 2. The manual does not change Loop 2 or the Live Layer."),

    page("feedback-statement","Feedback Statement","Feedback Statement gives you a dated record of the feedback you have submitted. Use it when you want to understand your learning record instead of looking at only one day.",["Choose a subject when the subject filter is shown.","Choose the date range you want to review.","Load the statement.","Read the feedback type, subject and topic.","Read your response and difficult concepts when available.","Check the credit change and running balance when shown.","Use the PDF action when you need a copy."],["Daily lecture feedback and doubt discussion feedback are kept in the statement flow.","The statement can combine records across the selected period when All Subjects is selected." ]),

    page("credits","Credits","Credits show the effect of your participation in the feedback system. They help you understand what you earned and what was deducted.",["Open the Credits area.","Read total earned credits.","Read credits spent or used when shown.","Read the available balance.","Check the feedback statement if you need to understand a credit change."],["A successful Daily Feedback submission earns +1 credit.","A successful Doubt Feedback response receives the same +1 treatment in the existing feedback credit flow.","A missed completed-day teacher log can create a −10 credit debit under the existing rule.","Today's pending feedback is not debited yet."],"These rules are documented from the existing Daily Feedback implementation. The manual does not change the credit engine."),

    page("progress","Progress Tracker","Progress Tracker shows your academic continuity and feedback patterns over time. Use it to find improvement, repeated difficulty and areas that need attention.",["Open Progress Tracker.","Choose a subject from the Subject control.","Read the headline metrics first.","Move through the calendar or period view.","Select a day when you need the daily status.","Read the weekly feedback breakdown.","Open Student Exam Preparation when you need the detailed unresolved-doubt preparation view."],["Tracked Days shows how many learning days are represented.","Satisfactory Feedbacks shows positive understanding feedback in the tracker.","Assistance Needed shows learning that needs more support.","Partially Understood shows lessons where understanding was not complete.","Satisfaction % gives the displayed satisfaction rate for the selected view.","Use the weekly breakdown to see whether a pattern is improving or repeating." ]),

    page("exam-preparation","Student Exam Preparation","Student Exam Preparation turns unresolved academic signals into a subject-wise preparation view. Use it to see what still needs attention before an exam.",["Open Student Exam Preparation from Progress Tracker when available.","Choose the Subject dropdown.","Choose the time range: Last 30 days, 60 days, 90 days or Custom.","Read the student-level preparation table.","Check unresolved doubts and the related topics.","Use the displayed risk or attention information to decide what to revise first."],["The table is designed to keep the existing academic intelligence result intact while letting you view it by subject and time period.","Use the topic and subtopic information to move from a number to a concrete revision area.","The page is a preparation view. It is not a new source of academic data."],"The filters are for viewing the existing preparation intelligence. They do not change Loop 1, Loop 2 or the Live Layer."),

    page("calendar","Topic Calendar","Topic Calendar places your classroom learning on a date-based view. It helps you remember what was taught and connect a day with its classroom evidence.",["Open Topic Calendar.","Choose the subject.","Choose the available date or period filter.","Move through the calendar.","Select a day to inspect the classroom record.","Read the topic and teacher information.","Open the day detail when available.","Use the day information to decide what needs revision."],["The calendar can show the assigned subject teacher.","A selected day can show lecture evidence such as topic, homework and classroom activity when those records exist.","The calendar can also show monthly classroom continuity." ]),

    page("worksheets","Worksheets / Study Material","Worksheets give you practice material published for your class and subject. You can open current work or search older published worksheets.",["Open Worksheets / Study Material.","Read the latest worksheet cards first.","Use View to open a worksheet.","Use Download PDF when you need an offline copy.","For older work, choose a subject.","Choose All time, 30, 60, 90 days or Custom dates.","Open the matching worksheet from the history table."],["A worksheet can contain multiple question sections.","The existing worksheet format supports MCQ, Fill in the Blanks, Match the Following, True / False, Short Answer, Long Answer, Picture / Image Based and Unseen Passage / Comprehension questions.","The history filter helps you find older published worksheets. It does not remove the latest worksheet area." ]),

    page("study-buddy","Study Buddy","Study Buddy creates targeted practice from your current unresolved doubts and the available worksheet material.",["Choose the subject.","Choose the worksheet period.","Review the worksheet sources used for the selected period.","Optionally add readable notebook files when the page allows it.","Generate the practice paper.","Review the paper before using it.","Preview or download the PDF.","Open History to revisit an earlier generated paper when available."],["Study Buddy starts from the latest unresolved doubts for the selected subject.","Questions are matched from the available worksheet corpus.","The generated paper is meant for targeted practice around current learning gaps." ]),

    page("read-data","How to read your academic data","Use the pages together. Do not judge your learning from one number only.",["Start with Daily Feedback to see how you understood a lesson.","Check Doubt Feedback for items that still need attention.","Use Progress Tracker to see the pattern over time.","Use Topic Calendar to find the lesson and date behind a pattern.","Use Worksheets to practise the relevant subject.","Use Study Buddy for targeted practice around unresolved doubts.","Recheck your later feedback to see whether the pattern changes."],["A percentage is a signal for the selected view and period.","A repeated topic or repeated doubt is more useful for revision than one isolated response.","Use the underlying topic and date whenever you want to understand why a metric changed."]),
  ]
};
