import type { PortalManualContent } from "./manualTypes";

const page=(id:string,title:string,summary:string,steps:string[],bullets?:string[],note?:string)=>({id,title,summary,steps,bullets,note});

export const TEACHER_MANUAL: PortalManualContent = {
  role:"teacher", label:"Teacher Portal", intro:"Use the Teacher Portal to record classroom evidence, review student learning signals, follow doubts, plan teaching and work with parents.", sections:[
    page("dashboard","Dashboard","Your starting point for the Teacher Portal. Use it to enter the academic workspace and reach the active teacher modules.",["Open Dashboard after login.","Read the information shown for your account and school.","Use the sidebar to open the module you need.","If a module is not enabled for your account, use the modules that are available to you."],["The active Teacher Portal workspace includes Daily Log, Class Health, Pending Doubts, Learning History, PTM, planners and Star Performers." ]),

    page("daily-log","Daily Log","Daily Log records what happened in a classroom on a teaching day. This evidence feeds the existing teacher intelligence and student academic flows.",["Open Daily Log.","Choose the relevant class, section or assignment.","Open the Daily Log dialog.","Enter the classroom information requested by the form.","Review the lecture, topic, homework and activity details before saving.","Publish or save using the existing action.","Wait for the save confirmation before closing."],["Daily Log creates the dated classroom evidence used by later intelligence views.","A completed teacher log is also part of the existing student feedback credit calculation."],"The Daily Log dialog is an existing feature. The manual does not change its fields or save logic."),

    page("daily-log-sections","Daily Log: what the classroom record means","The Daily Log is more than a save form. Its record can explain the classroom evidence behind later analytics.",["Check the class and subject before saving.","Check the topic taught for the day.","Record homework when homework was given.","Record the classroom activity when an activity was performed.","Review the date before publishing."],["Topic tells you what learning was covered.","Homework tells you what follow-up work was assigned.","Activity records the classroom activity signal when one exists.","The date connects the record to Learning History, Class Health and school intelligence." ]),

    page("teaching-journal","Class Health","Class Health shows classroom understanding and feedback patterns. Use it to see whether students understood the latest learning and where support may be needed.",["Open Class Health.","Choose the relevant classroom when the page provides a classroom selector.","Read the latest lecture information.","Read Students Filled Feedback and Feedback Remaining.","Compare Completely Understood, Partially Understood and Didn't Understand.","Read Class Health Score.","Check the Most Difficult Concept.","Review Students Requiring Attention.","Use the classroom pattern to decide the next teaching action."],["Latest Lecture Date tells you which lecture the evidence belongs to.","Latest Topic shows the latest recorded topic.","Students Filled Feedback shows participation in student feedback.","Feedback Remaining shows the feedback still missing for the selected classroom evidence.","Completely Understood, Partially Understood and Didn't Understand show the response mix.","Class Health Score is shown on a 0–100 scale in the classroom ledger.","Most Difficult Concept points to a repeated learning difficulty when available.","Students Requiring Attention identifies students the existing intelligence marks for follow-up." ]),

    page("exam-preparation","Pending Doubts","Pending Doubts is the teacher view for student doubts that still need attention.",["Open Pending Doubts.","Read the student and topic information.","Check the doubt details.","Open the relevant item when more information is available.","Use the existing acknowledgement or resolution action.","Return to the list and confirm the updated status."],["Look for repeated doubts on the same topic.","A repeated topic can be more important than one isolated doubt.","Use the doubt information together with Class Health and Learning History." ]),

    page("my-classroom","Learning History","Learning History lets you inspect your assigned classroom, teaching history and the daily learning record behind the classroom pattern.",["Open Learning History.","Choose the assigned classroom.","Read the class, section, subject and session information.","Move through the classroom calendar.","Select a day.","Read the Latest Lecture information.","Check homework and classroom activity for that day.","Open Topics when more topics are available.","Review Monthly Classroom Summary.","Check Students Requiring Attention when shown."],["Monthly Classroom Summary can show Total Lectures, Homework Days, Activity Days and Completed Topics.","Students Requiring Attention is a follow-up list, not a replacement for the detailed student evidence.","Use the date and topic behind a signal before deciding what action to take." ]),

    page("topics-popup","Topics Popup","The Topics popup gives the detailed topic record for a selected day in Learning History.",["Select a day in Learning History.","Open the topics view.","Read the topics taught that day.","Check the topic detail and the available PAGES, HOMEWORK and ACTIVITY information.","Close the popup to return to Learning History."],["The popup is useful when the calendar shows that a day had more than one topic.","Use it to connect a classroom metric with the actual lesson content."],"This popup belongs to the existing Learning History feature. The manual does not modify it."),

    page("ptm","PTM","PTM supports the parent-teacher meeting workflow. Use the existing controls to prepare and manage the meeting record.",["Open PTM.","Review the available meeting information.","Check the student or parent context shown by the page.","Use the existing PTM actions.","Complete the meeting workflow shown on screen.","Use available PDF or communication actions when required."],["Use PTM together with Learning History when you need classroom evidence for a parent discussion." ]),

    page("lesson-planner","Lesson Planner","Lesson Planner is the teaching planning workspace.",["Open Lesson Planner.","Choose the class, subject and planning period shown by the page.","Create or edit the lesson plan.","Review the planned topic and teaching details.","Save the plan.","Use preview or other existing actions when available."],["The school can later use planner audit information to review planning activity." ]),

    page("worksheet-planner","Worksheet Planner","Worksheet Planner lets you create and manage practice worksheets.",["Open Worksheet Planner.","Choose the class and subject.","Build the worksheet with the existing controls.","Review the questions and sections.","Preview the worksheet.","Save or publish using the existing action."],["The student worksheet view supports several question types, so review the final worksheet before publishing." ]),

    page("unit-test-planner","Unit Test Planner","Unit Test Planner is used to prepare unit tests for a class and subject.",["Open Unit Test Planner.","Choose the class, subject and unit.","Enter the test details.","Review the planned test.","Save or publish using the existing controls."],["School Admin can see the related planning activity in Unit Test Audit." ]),

    page("exam-paper-planner","Exam Paper Planner","Exam Paper Planner is used to prepare exam papers.",["Open Exam Paper Planner.","Choose the relevant class and subject.","Add or select the required paper content.","Review the paper.","Save, preview or download with the existing controls."],["Use the final preview to check that the paper content is complete before sharing it." ]),

    page("star-performers","Star Performers","Star Performers shows recognition information for students or classroom performance in the existing portal.",["Open Star Performers.","Read the displayed recognition information.","Use the available period or filter controls.","Open the detail when available.","Use the information as a recognition view alongside detailed classroom evidence." ]),

    page("data-reading","How to read Teacher Intelligence","Teacher Intelligence works best when you connect a metric to the class, date, topic and student evidence behind it.",["Start with the current page signal.","Check the class, subject and period.","Look at the underlying student or topic detail.","Look for repeated patterns.","Use Daily Log and Learning History to understand the classroom context.","Use Pending Doubts when the signal is a learning gap.","Take the next action in the relevant teaching workflow."],["Feedback percentages describe the selected evidence set.","Class Health is a classroom signal, not a final judgement about a student.","A repeated difficult concept is a useful reason to inspect the lesson and practice material.","Use student-level detail before making a student-specific decision."])
  ]
};
